Add query & write series API definitions.
moreOver0/azure-rest-api-specs pull request #1
Opened 2019-05-28 08:11 UTC by tiraffe

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-28 13:29 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "Timeseries": {
make this called "Points"

2019-05-28 13:29 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +              "$ref": "#/definitions/Timeseries"
Timeseries -> Points

2019-05-28 13:31 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +              "$ref": "#/definitions/QueryRequest"
change to some other name

2019-05-29 03:13 UTC, moreOver0 requested changes

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +              "$ref": "#/definitions/QueryResponse"
TimeSeriesQueryResponse

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +            "$ref": "./examples/QuerySeries.json"
TimeSeriesQuery.json

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +          "items": {
define a Enum type please. Refer to https://github.com/moreOver0/azure-rest-api-specs/blob/43d7d1914f04983be88346e7bd33723d9ef4393c/specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json#L293

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +          "items": {
no "none"

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "QueryRequest": {
change name

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "QueryResponse": {
change name

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +      "properties": {
"required" list

2019-05-29 03:13 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +      "properties": {
"required" list

2019-05-29 04:09 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +        "operationId": "Timeseries_Write",
TimeSeries_Write_Post

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +        "operationId": "Timeseries_Write",
TimeSeries_Write

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +        "operationId": "Timeseries_Query",
TimeSeries_Query

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "Point": {
Can use the original Point in AnomalyDetection.json

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +              "$ref": "#/definitions/Points"
{
           "type": "array",
          "description": "Time series data points.",
          "items": {
            "$ref": "#/definitions/Point"
          }

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "Points": {
remove points

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/QueryWriteSeries.json
> +    "timeseriesId": {
remove this we will have a common one

2019-05-29 05:18 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/examples/TimeSeriesWrite.json
> +      "series": [
remove series, just a list of points

2019-05-29 06:17 UTC, merged